# Generated by Django 4.2.1 on 2023-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='login',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
