# Generated by Django 4.2.1 on 2023-05-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('idCarro', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca_modelo', models.CharField(max_length=300)),
                ('cor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idUsuario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Estacionamentos',
            fields=[
                ('idEstacionamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True, help_text='Formato <em>YYYY-MM-DD</em>')),
                ('hora_entrada', models.TimeField(auto_now_add=True, help_text='Formato <em>HH-MM-SS</em>')),
                ('data_saida', models.DateField(blank=True, help_text='Formato <em>YYYY-MM-DD</em>', null=True)),
                ('hora_saida', models.TimeField(blank=True, help_text='Formato <em>HH-MM-SS</em>', null=True)),
                ('fk_IdCarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carros')),
            ],
        ),
        migrations.AddField(
            model_name='carros',
            name='fk_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
