# Generated by Django 4.2.1 on 2023-05-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carros_alter_usuarios_idusuario_estacionamentos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='estacionamentos',
            options={'verbose_name_plural': 'Estacionamentos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='estacionamentos',
            name='fk_IdCarro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carros', verbose_name='Placa do Carro'),
        ),
    ]
